Issue 65 - data validation on contact form, company and facility detail forms
NREL/NEB-Tool pull request #132
Opened 2024-06-18 15:57 UTC by RLiNREL

Implemented data validation
#114 added validation to company name and zip code
#115 added validation to name (first and last name), phone number, and email
#117 same with 114

2024-06-26 19:13 UTC, jordanperr commented
I tested the latest version v0.0.1-alpha-03c6da6.
- Zip code validation does not seem to be implemented.
- "New Company" should be removed as a default value from company name field. Just leave it empty.
- Badges in the sidebar have not yet been merged into this PR.

Perhaps out of scope for this pull request, I noticed the other fields in the General Information tab are not yet validated.

2024-07-10 13:45 UTC, rmroot requested changes
Overall looks good. Please remove commented out debugging code

2024-07-10 13:45 UTC, rmroot commented on src/app/setup-wizard/pre-visit/company-contacts-setup/company-contacts-form/company-contacts-form.service.ts
> +    // console.log('phone:', phone, 'ext:', ext, 'phext:', phoneWithExt);
Please remove commented out debugging logs

2024-07-10 14:34 UTC, RLiNREL commented on src/app/setup-wizard/pre-visit/company-contacts-setup/company-contacts-form/company-contacts-form.service.ts
> +    // console.log('phone:', phone, 'ext:', ext, 'phext:', phoneWithExt);
Thanks! They have been removed.

2024-07-15 18:40 UTC, rmroot approved these changes

2024-07-15 18:40 UTC, merged