Issue 65: fix a bug with contact name, remove default facility name, validation persistence
NREL/NEB-Tool pull request #164
Opened 2024-07-17 18:07 UTC by RLiNREL

1. Contact name bug fixed to make sure first name is saved if only one name is provided instead of first + last name)
2. default "New Facility" is changed to empty string
3. Company details page: the validation warning message should persist when navigating out and back into the page.

2024-07-17 19:58 UTC, rmroot requested changes

2024-07-17 19:58 UTC, rmroot commented on src/app/shared/shared-settings-forms/shared-settings-forms.service.ts
> +      electricityPrice: [unitSettings.electricityPrice, [Validators.required, Validators.min(0)]],
For all of these we would only want to require the value if they are included.

2024-07-18 14:42 UTC, rmroot approved these changes

2024-07-18 14:42 UTC, rmroot commented on src/app/shared/shared-settings-forms/shared-settings-forms.service.ts
> +  setRequiredValidator(control: AbstractControl, isRequired: boolean) {
Very nice solution.

2024-07-18 14:42 UTC, merged

2024-07-18 14:43 UTC, RLiNREL commented on src/app/shared/shared-settings-forms/shared-settings-forms.service.ts
> +      electricityPrice: [unitSettings.electricityPrice, [Validators.required, Validators.min(0)]],
Dynamically add or remove required validator to the utilities based on the "include" check boxes.